[build]
  command = "npm install && npm run build && cp _redirects dist/public/ || cp client/public/_redirects dist/public/ || true"
  publish = "dist/public"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

# Redirect all requests to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[functions]
  directory = "netlify/functions"
  
[[redirects]]
  from = "/api/accounts/connect/instagram"
  to = "/.netlify/functions/instagram-connect"
  status = 200
  force = true